# Generated by Django 4.0.3 on 2022-04-26 11:37

import dashboard.models
import dashboard.validators
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=dashboard.models.excel_dir_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('xlsx',), message='File is not an Excel format.'), dashboard.validators.FileValidator(content_types=('application/zip', 'application/xlsx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'), max_size=None, tests=(dashboard.validators.is_excel_file,))])),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
